#ifndef ZLEMU_CORE_SMS_TESTS_Z80OPCODES_H
#define ZLEMU_CORE_SMS_TESTS_Z80OPCODES_H

#include <array>
#include <stdint.h>

struct TestOpcodeInfo
{
    const char *opcode;
    const char *name;
};

inline constexpr std::array<TestOpcodeInfo, 256> TestOpcodeTable = {{
    {"00", "NOP"},
    {"01", "LD_BC_nn"},
    {"02", "LD_ptr_BC_A"},
    {"03", "INC_BC"},
    {"04", "INC_B"},
    {"05", "DEC_B"},
    {"06", "LD_B_n"},
    {"07", "RLCA"},
    {"08", "EX_AF_AF_"},
    {"09", "ADD_HL_BC"},
    {"0A", "LD_A_ptr_BC"},
    {"0B", "DEC_BC"},
    {"0C", "INC_C"},
    {"0D", "DEC_C"},
    {"0E", "LD_C_n"},
    {"0F", "RRCA"},
    {"10", "DJNZ_d"},
    {"11", "LD_DE_nn"},
    {"12", "LD_ptr_DE_A"},
    {"13", "INC_DE"},
    {"14", "INC_D"},
    {"15", "DEC_D"},
    {"16", "LD_D_n"},
    {"17", "RLA"},
    {"18", "JR_d"},
    {"19", "ADD_HL_DE"},
    {"1A", "LD_A_ptr_DE"},
    {"1B", "DEC_DE"},
    {"1C", "INC_E"},
    {"1D", "DEC_E"},
    {"1E", "LD_E_n"},
    {"1F", "RRA"},
    {"20", "JR_NZ_d"},
    {"21", "LD_HL_nn"},
    {"22", "LD_ptr_nn_HL"},
    {"23", "INC_HL"},
    {"24", "INC_H"},
    {"25", "DEC_H"},
    {"26", "LD_H_n"},
    {"27", "DAA"},
    {"28", "JR_Z_d"},
    {"29", "ADD_HL_HL"},
    {"2A", "LD_HL_ptr_nn"},
    {"2B", "DEC_HL"},
    {"2C", "INC_L"},
    {"2D", "DEC_L"},
    {"2E", "LD_L_n"},
    {"2F", "CPL"},
    {"30", "JR_NC_d"},
    {"31", "LD_SP_nn"},
    {"32", "LD_ptr_nn_A"},
    {"33", "INC_SP"},
    {"34", "INC_ptr_HL"},
    {"35", "DEC_ptr_HL"},
    {"36", "LD_ptr_HL_n"},
    {"37", "SCF"},
    {"38", "JR_C_d"},
    {"39", "ADD_HL_SP"},
    {"3A", "LD_A_ptr_nn"},
    {"3B", "DEC_SP"},
    {"3C", "INC_A"},
    {"3D", "DEC_A"},
    {"3E", "LD_A_n"},
    {"3F", "CCF"},
    {"40", "LD_B_B"},
    {"41", "LD_B_C"},
    {"42", "LD_B_D"},
    {"43", "LD_B_E"},
    {"44", "LD_B_H"},
    {"45", "LD_B_L"},
    {"46", "LD_B_ptr_HL"},
    {"47", "LD_B_A"},
    {"48", "LD_C_B"},
    {"49", "LD_C_C"},
    {"4A", "LD_C_D"},
    {"4B", "LD_C_E"},
    {"4C", "LD_C_H"},
    {"4D", "LD_C_L"},
    {"4E", "LD_C_ptr_HL"},
    {"4F", "LD_C_A"},
    {"50", "LD_D_B"},
    {"51", "LD_D_C"},
    {"52", "LD_D_D"},
    {"53", "LD_D_E"},
    {"54", "LD_D_H"},
    {"55", "LD_D_L"},
    {"56", "LD_D_ptr_HL"},
    {"57", "LD_D_A"},
    {"58", "LD_E_B"},
    {"59", "LD_E_C"},
    {"5A", "LD_E_D"},
    {"5B", "LD_E_E"},
    {"5C", "LD_E_H"},
    {"5D", "LD_E_L"},
    {"5E", "LD_E_ptr_HL"},
    {"5F", "LD_E_A"},
    {"60", "LD_H_B"},
    {"61", "LD_H_C"},
    {"62", "LD_H_D"},
    {"63", "LD_H_E"},
    {"64", "LD_H_H"},
    {"65", "LD_H_L"},
    {"66", "LD_H_ptr_HL"},
    {"67", "LD_H_A"},
    {"68", "LD_L_B"},
    {"69", "LD_L_C"},
    {"6A", "LD_L_D"},
    {"6B", "LD_L_E"},
    {"6C", "LD_L_H"},
    {"6D", "LD_L_L"},
    {"6E", "LD_L_ptr_HL"},
    {"6F", "LD_L_A"},
    {"70", "LD_ptr_HL_B"},
    {"71", "LD_ptr_HL_C"},
    {"72", "LD_ptr_HL_D"},
    {"73", "LD_ptr_HL_E"},
    {"74", "LD_ptr_HL_H"},
    {"75", "LD_ptr_HL_L"},
    {"76", "HALT"},
    {"77", "LD_ptr_HL_A"},
    {"78", "LD_A_B"},
    {"79", "LD_A_C"},
    {"7A", "LD_A_D"},
    {"7B", "LD_A_E"},
    {"7C", "LD_A_H"},
    {"7D", "LD_A_L"},
    {"7E", "LD_A_ptr_HL"},
    {"7F", "LD_A_A"},
    {"80", "ADD_A_B"},
    {"81", "ADD_A_C"},
    {"82", "ADD_A_D"},
    {"83", "ADD_A_E"},
    {"84", "ADD_A_H"},
    {"85", "ADD_A_L"},
    {"86", "ADD_A_ptr_HL"},
    {"87", "ADD_A_A"},
    {"88", "ADC_A_B"},
    {"89", "ADC_A_C"},
    {"8A", "ADC_A_D"},
    {"8B", "ADC_A_E"},
    {"8C", "ADC_A_H"},
    {"8D", "ADC_A_L"},
    {"8E", "ADC_A_ptr_HL"},
    {"8F", "ADC_A_A"},
    {"90", "SUB_B"},
    {"91", "SUB_C"},
    {"92", "SUB_D"},
    {"93", "SUB_E"},
    {"94", "SUB_H"},
    {"95", "SUB_L"},
    {"96", "SUB_ptr_HL"},
    {"97", "SUB_A"},
    {"98", "SBC_A_B"},
    {"99", "SBC_A_C"},
    {"9A", "SBC_A_D"},
    {"9B", "SBC_A_E"},
    {"9C", "SBC_A_H"},
    {"9D", "SBC_A_L"},
    {"9E", "SBC_A_ptr_HL"},
    {"9F", "SBC_A_A"},
    {"A0", "AND_B"},
    {"A1", "AND_C"},
    {"A2", "AND_D"},
    {"A3", "AND_E"},
    {"A4", "AND_H"},
    {"A5", "AND_L"},
    {"A6", "AND_ptr_HL"},
    {"A7", "AND_A"},
    {"A8", "XOR_B"},
    {"A9", "XOR_C"},
    {"AA", "XOR_D"},
    {"AB", "XOR_E"},
    {"AC", "XOR_H"},
    {"AD", "XOR_L"},
    {"AE", "XOR_ptr_HL"},
    {"AF", "XOR_A"},
    {"B0", "OR_B"},
    {"B1", "OR_C"},
    {"B2", "OR_D"},
    {"B3", "OR_E"},
    {"B4", "OR_H"},
    {"B5", "OR_L"},
    {"B6", "OR_ptr_HL"},
    {"B7", "OR_A"},
    {"B8", "CP_B"},
    {"B9", "CP_C"},
    {"BA", "CP_D"},
    {"BB", "CP_E"},
    {"BC", "CP_H"},
    {"BD", "CP_L"},
    {"BE", "CP_ptr_HL"},
    {"BF", "CP_A"},
    {"C0", "RET_NZ"},
    {"C1", "POP_BC"},
    {"C2", "JP_NZ_nn"},
    {"C3", "JP_nn"},
    {"C4", "CALL_NZ_nn"},
    {"C5", "PUSH_BC"},
    {"C6", "ADD_A_n"},
    {"C7", "RST_0"},
    {"C8", "RET_Z"},
    {"C9", "RET"},
    {"CA", "JP_Z_nn"},
    {"CB", "_Prefix_"},
    {"CC", "CALL_Z_nn"},
    {"CD", "CALL_nn"},
    {"CE", "ADC_A_n"},
    {"CF", "RST_8"},
    {"D0", "RET_NC"},
    {"D1", "POP_DE"},
    {"D2", "JP_NC_nn"},
    {"D3", "OUT_ptr_n_A"},
    {"D4", "CALL_NC_nn"},
    {"D5", "PUSH_DE"},
    {"D6", "SUB_n"},
    {"D7", "RST_10H"},
    {"D8", "RET_C"},
    {"D9", "EXX"},
    {"DA", "JP_C_nn"},
    {"DB", "IN_A_ptr_n"},
    {"DC", "CALL_C_nn"},
    {"DD", "_IX_Prefix_"},
    {"DE", "SBC_A_n"},
    {"DF", "RST_18H"},
    {"E0", "RET_PO"},
    {"E1", "POP_HL"},
    {"E2", "JP_PO_nn"},
    {"E3", "EX_ptr_SP_HL"},
    {"E4", "CALL_PO_nn"},
    {"E5", "PUSH_HL"},
    {"E6", "AND_n"},
    {"E7", "RST_20H"},
    {"E8", "RET_PE"},
    {"E9", "JP_ptr_HL"},
    {"EA", "JP_PE_nn"},
    {"EB", "EX_DE_HL"},
    {"EC", "CALL_PE_nn"},
    {"ED", "_Prefix_"},
    {"EE", "XOR_n"},
    {"EF", "RST_28H"},
    {"F0", "RET_P"},
    {"F1", "POP_AF"},
    {"F2", "JP_P_nn"},
    {"F3", "DI"},
    {"F4", "CALL_P_nn"},
    {"F5", "PUSH_AF"},
    {"F6", "OR_n"},
    {"F7", "RST_30H"},
    {"F8", "RET_M"},
    {"F9", "LD_SP_HL"},
    {"FA", "JP_M_nn"},
    {"FB", "EI"},
    {"FC", "CALL_M_nn"},
    {"FD", "_IY_Prefix_"},
    {"FE", "CP_n"},
    {"FF", "RST_38H"},
}};

inline constexpr std::array<TestOpcodeInfo, 256> TestOpcodeTableCB = {{
    {"CB 00", "RLC_B"},
    {"CB 01", "RLC_C"},
    {"CB 02", "RLC_D"},
    {"CB 03", "RLC_E"},
    {"CB 04", "RLC_H"},
    {"CB 05", "RLC_L"},
    {"CB 06", "RLC_ptr_HL"},
    {"CB 07", "RLC_A"},
    {"CB 08", "RRC_B"},
    {"CB 09", "RRC_C"},
    {"CB 0A", "RRC_D"},
    {"CB 0B", "RRC_E"},
    {"CB 0C", "RRC_H"},
    {"CB 0D", "RRC_L"},
    {"CB 0E", "RRC_ptr_HL"},
    {"CB 0F", "RRC_A"},
    {"CB 10", "RL_B"},
    {"CB 11", "RL_C"},
    {"CB 12", "RL_D"},
    {"CB 13", "RL_E"},
    {"CB 14", "RL_H"},
    {"CB 15", "RL_L"},
    {"CB 16", "RL_ptr_HL"},
    {"CB 17", "RL_A"},
    {"CB 18", "RR_B"},
    {"CB 19", "RR_C"},
    {"CB 1A", "RR_D"},
    {"CB 1B", "RR_E"},
    {"CB 1C", "RR_H"},
    {"CB 1D", "RR_L"},
    {"CB 1E", "RR_ptr_HL"},
    {"CB 1F", "RR_A"},
    {"CB 20", "SLA_B"},
    {"CB 21", "SLA_C"},
    {"CB 22", "SLA_D"},
    {"CB 23", "SLA_E"},
    {"CB 24", "SLA_H"},
    {"CB 25", "SLA_L"},
    {"CB 26", "SLA_ptr_HL"},
    {"CB 27", "SLA_A"},
    {"CB 28", "SRA_B"},
    {"CB 29", "SRA_C"},
    {"CB 2A", "SRA_D"},
    {"CB 2B", "SRA_E"},
    {"CB 2C", "SRA_H"},
    {"CB 2D", "SRA_L"},
    {"CB 2E", "SRA_ptr_HL"},
    {"CB 2F", "SRA_A"},
    {"CB 30", "SLL_B"},
    {"CB 31", "SLL_C"},
    {"CB 32", "SLL_D"},
    {"CB 33", "SLL_E"},
    {"CB 34", "SLL_H"},
    {"CB 35", "SLL_L"},
    {"CB 36", "SLL_ptr_HL"},
    {"CB 37", "SLL_A"},
    {"CB 38", "SRL_B"},
    {"CB 39", "SRL_C"},
    {"CB 3A", "SRL_D"},
    {"CB 3B", "SRL_E"},
    {"CB 3C", "SRL_H"},
    {"CB 3D", "SRL_L"},
    {"CB 3E", "SRL_ptr_HL"},
    {"CB 3F", "SRL_A"},
    {"CB 40", "BIT_0_B"},
    {"CB 41", "BIT_0_C"},
    {"CB 42", "BIT_0_D"},
    {"CB 43", "BIT_0_E"},
    {"CB 44", "BIT_0_H"},
    {"CB 45", "BIT_0_L"},
    {"CB 46", "BIT_0_ptr_HL"},
    {"CB 47", "BIT_0_A"},
    {"CB 48", "BIT_1_B"},
    {"CB 49", "BIT_1_C"},
    {"CB 4A", "BIT_1_D"},
    {"CB 4B", "BIT_1_E"},
    {"CB 4C", "BIT_1_H"},
    {"CB 4D", "BIT_1_L"},
    {"CB 4E", "BIT_1_ptr_HL"},
    {"CB 4F", "BIT_1_A"},
    {"CB 50", "BIT_2_B"},
    {"CB 51", "BIT_2_C"},
    {"CB 52", "BIT_2_D"},
    {"CB 53", "BIT_2_E"},
    {"CB 54", "BIT_2_H"},
    {"CB 55", "BIT_2_L"},
    {"CB 56", "BIT_2_ptr_HL"},
    {"CB 57", "BIT_2_A"},
    {"CB 58", "BIT_3_B"},
    {"CB 59", "BIT_3_C"},
    {"CB 5A", "BIT_3_D"},
    {"CB 5B", "BIT_3_E"},
    {"CB 5C", "BIT_3_H"},
    {"CB 5D", "BIT_3_L"},
    {"CB 5E", "BIT_3_ptr_HL"},
    {"CB 5F", "BIT_3_A"},
    {"CB 60", "BIT_4_B"},
    {"CB 61", "BIT_4_C"},
    {"CB 62", "BIT_4_D"},
    {"CB 63", "BIT_4_E"},
    {"CB 64", "BIT_4_H"},
    {"CB 65", "BIT_4_L"},
    {"CB 66", "BIT_4_ptr_HL"},
    {"CB 67", "BIT_4_A"},
    {"CB 68", "BIT_5_B"},
    {"CB 69", "BIT_5_C"},
    {"CB 6A", "BIT_5_D"},
    {"CB 6B", "BIT_5_E"},
    {"CB 6C", "BIT_5_H"},
    {"CB 6D", "BIT_5_L"},
    {"CB 6E", "BIT_5_ptr_HL"},
    {"CB 6F", "BIT_5_A"},
    {"CB 70", "BIT_6_B"},
    {"CB 71", "BIT_6_C"},
    {"CB 72", "BIT_6_D"},
    {"CB 73", "BIT_6_E"},
    {"CB 74", "BIT_6_H"},
    {"CB 75", "BIT_6_L"},
    {"CB 76", "BIT_6_ptr_HL"},
    {"CB 77", "BIT_6_A"},
    {"CB 78", "BIT_7_B"},
    {"CB 79", "BIT_7_C"},
    {"CB 7A", "BIT_7_D"},
    {"CB 7B", "BIT_7_E"},
    {"CB 7C", "BIT_7_H"},
    {"CB 7D", "BIT_7_L"},
    {"CB 7E", "BIT_7_ptr_HL"},
    {"CB 7F", "BIT_7_A"},
    {"CB 80", "RES_0_B"},
    {"CB 81", "RES_0_C"},
    {"CB 82", "RES_0_D"},
    {"CB 83", "RES_0_E"},
    {"CB 84", "RES_0_H"},
    {"CB 85", "RES_0_L"},
    {"CB 86", "RES_0_ptr_HL"},
    {"CB 87", "RES_0_A"},
    {"CB 88", "RES_1_B"},
    {"CB 89", "RES_1_C"},
    {"CB 8A", "RES_1_D"},
    {"CB 8B", "RES_1_E"},
    {"CB 8C", "RES_1_H"},
    {"CB 8D", "RES_1_L"},
    {"CB 8E", "RES_1_ptr_HL"},
    {"CB 8F", "RES_1_A"},
    {"CB 90", "RES_2_B"},
    {"CB 91", "RES_2_C"},
    {"CB 92", "RES_2_D"},
    {"CB 93", "RES_2_E"},
    {"CB 94", "RES_2_H"},
    {"CB 95", "RES_2_L"},
    {"CB 96", "RES_2_ptr_HL"},
    {"CB 97", "RES_2_A"},
    {"CB 98", "RES_3_B"},
    {"CB 99", "RES_3_C"},
    {"CB 9A", "RES_3_D"},
    {"CB 9B", "RES_3_E"},
    {"CB 9C", "RES_3_H"},
    {"CB 9D", "RES_3_L"},
    {"CB 9E", "RES_3_ptr_HL"},
    {"CB 9F", "RES_3_A"},
    {"CB A0", "RES_4_B"},
    {"CB A1", "RES_4_C"},
    {"CB A2", "RES_4_D"},
    {"CB A3", "RES_4_E"},
    {"CB A4", "RES_4_H"},
    {"CB A5", "RES_4_L"},
    {"CB A6", "RES_4_ptr_HL"},
    {"CB A7", "RES_4_A"},
    {"CB A8", "RES_5_B"},
    {"CB A9", "RES_5_C"},
    {"CB AA", "RES_5_D"},
    {"CB AB", "RES_5_E"},
    {"CB AC", "RES_5_H"},
    {"CB AD", "RES_5_L"},
    {"CB AE", "RES_5_ptr_HL"},
    {"CB AF", "RES_5_A"},
    {"CB B0", "RES_6_B"},
    {"CB B1", "RES_6_C"},
    {"CB B2", "RES_6_D"},
    {"CB B3", "RES_6_E"},
    {"CB B4", "RES_6_H"},
    {"CB B5", "RES_6_L"},
    {"CB B6", "RES_6_ptr_HL"},
    {"CB B7", "RES_6_A"},
    {"CB B8", "RES_7_B"},
    {"CB B9", "RES_7_C"},
    {"CB BA", "RES_7_D"},
    {"CB BB", "RES_7_E"},
    {"CB BC", "RES_7_H"},
    {"CB BD", "RES_7_L"},
    {"CB BE", "RES_7_ptr_HL"},
    {"CB BF", "RES_7_A"},
    {"CB C0", "SET_0_B"},
    {"CB C1", "SET_0_C"},
    {"CB C2", "SET_0_D"},
    {"CB C3", "SET_0_E"},
    {"CB C4", "SET_0_H"},
    {"CB C5", "SET_0_L"},
    {"CB C6", "SET_0_ptr_HL"},
    {"CB C7", "SET_0_A"},
    {"CB C8", "SET_1_B"},
    {"CB C9", "SET_1_C"},
    {"CB CA", "SET_1_D"},
    {"CB CB", "SET_1_E"},
    {"CB CC", "SET_1_H"},
    {"CB CD", "SET_1_L"},
    {"CB CE", "SET_1_ptr_HL"},
    {"CB CF", "SET_1_A"},
    {"CB D0", "SET_2_B"},
    {"CB D1", "SET_2_C"},
    {"CB D2", "SET_2_D"},
    {"CB D3", "SET_2_E"},
    {"CB D4", "SET_2_H"},
    {"CB D5", "SET_2_L"},
    {"CB D6", "SET_2_ptr_HL"},
    {"CB D7", "SET_2_A"},
    {"CB D8", "SET_3_B"},
    {"CB D9", "SET_3_C"},
    {"CB DA", "SET_3_D"},
    {"CB DB", "SET_3_E"},
    {"CB DC", "SET_3_H"},
    {"CB DD", "SET_3_L"},
    {"CB DE", "SET_3_ptr_HL"},
    {"CB DF", "SET_3_A"},
    {"CB E0", "SET_4_B"},
    {"CB E1", "SET_4_C"},
    {"CB E2", "SET_4_D"},
    {"CB E3", "SET_4_E"},
    {"CB E4", "SET_4_H"},
    {"CB E5", "SET_4_L"},
    {"CB E6", "SET_4_ptr_HL"},
    {"CB E7", "SET_4_A"},
    {"CB E8", "SET_5_B"},
    {"CB E9", "SET_5_C"},
    {"CB EA", "SET_5_D"},
    {"CB EB", "SET_5_E"},
    {"CB EC", "SET_5_H"},
    {"CB ED", "SET_5_L"},
    {"CB EE", "SET_5_ptr_HL"},
    {"CB EF", "SET_5_A"},
    {"CB F0", "SET_6_B"},
    {"CB F1", "SET_6_C"},
    {"CB F2", "SET_6_D"},
    {"CB F3", "SET_6_E"},
    {"CB F4", "SET_6_H"},
    {"CB F5", "SET_6_L"},
    {"CB F6", "SET_6_ptr_HL"},
    {"CB F7", "SET_6_A"},
    {"CB F8", "SET_7_B"},
    {"CB F9", "SET_7_C"},
    {"CB FA", "SET_7_D"},
    {"CB FB", "SET_7_E"},
    {"CB FC", "SET_7_H"},
    {"CB FD", "SET_7_L"},
    {"CB FE", "SET_7_ptr_HL"},
    {"CB FF", "SET_7_A"},
}};

inline constexpr std::array<TestOpcodeInfo, 256> TestOpcodeTableDD = {{
    {"DD 00", "NOP"},
    {"DD 01", "LD_BC_nn"},
    {"DD 02", "LD_ptr_BC_A"},
    {"DD 03", "INC_BC"},
    {"DD 04", "INC_B"},
    {"DD 05", "DEC_B"},
    {"DD 06", "LD_B_n"},
    {"DD 07", "RLCA"},
    {"DD 08", "EX_AF_AF_"},
    {"DD 09", "ADD_IX_BC"},
    {"DD 0A", "LD_A_ptr_BC"},
    {"DD 0B", "DEC_BC"},
    {"DD 0C", "INC_C"},
    {"DD 0D", "DEC_C"},
    {"DD 0E", "LD_C_n"},
    {"DD 0F", "RRCA"},
    {"DD 10", "DJNZ_d"},
    {"DD 11", "LD_DE_nn"},
    {"DD 12", "LD_ptr_DE_A"},
    {"DD 13", "INC_DE"},
    {"DD 14", "INC_D"},
    {"DD 15", "DEC_D"},
    {"DD 16", "LD_D_n"},
    {"DD 17", "RLA"},
    {"DD 18", "JR_d"},
    {"DD 19", "ADD_IX_DE"},
    {"DD 1A", "LD_A_ptr_DE"},
    {"DD 1B", "DEC_DE"},
    {"DD 1C", "INC_E"},
    {"DD 1D", "DEC_E"},
    {"DD 1E", "LD_E_n"},
    {"DD 1F", "RRA"},
    {"DD 20", "JR_NZ_d"},
    {"DD 21", "LD_IX_nn"},
    {"DD 22", "LD_ptr_nn_IX"},
    {"DD 23", "INC_IX"},
    {"DD 24", "INC_IXh"},
    {"DD 25", "DEC_IXh"},
    {"DD 26", "LD_IXh_n"},
    {"DD 27", "DAA"},
    {"DD 28", "JR_Z_d"},
    {"DD 29", "ADD_IX_IX"},
    {"DD 2A", "LD_IX_ptr_nn"},
    {"DD 2B", "DEC_IX"},
    {"DD 2C", "INC_IXl"},
    {"DD 2D", "DEC_IXl"},
    {"DD 2E", "LD_IXl_n"},
    {"DD 2F", "CPL"},
    {"DD 30", "JR_NC_d"},
    {"DD 31", "LD_SP_nn"},
    {"DD 32", "LD_ptr_nn_A"},
    {"DD 33", "INC_SP"},
    {"DD 34", "INC_ptr_IX_d"},
    {"DD 35", "DEC_ptr_IX_d"},
    {"DD 36", "LD_ptr_IX_d_n"},
    {"DD 37", "SCF"},
    {"DD 38", "JR_C_d"},
    {"DD 39", "ADD_IX_SP"},
    {"DD 3A", "LD_A_ptr_nn"},
    {"DD 3B", "DEC_SP"},
    {"DD 3C", "INC_A"},
    {"DD 3D", "DEC_A"},
    {"DD 3E", "LD_A_n"},
    {"DD 3F", "CCF"},
    {"DD 40", "LD_B_B"},
    {"DD 41", "LD_B_C"},
    {"DD 42", "LD_B_D"},
    {"DD 43", "LD_B_E"},
    {"DD 44", "LD_B_IXh"},
    {"DD 45", "LD_B_IXl"},
    {"DD 46", "LD_B_ptr_IX_d"},
    {"DD 47", "LD_B_A"},
    {"DD 48", "LD_C_B"},
    {"DD 49", "LD_C_C"},
    {"DD 4A", "LD_C_D"},
    {"DD 4B", "LD_C_E"},
    {"DD 4C", "LD_C_IXh"},
    {"DD 4D", "LD_C_IXl"},
    {"DD 4E", "LD_C_ptr_IX_d"},
    {"DD 4F", "LD_C_A"},
    {"DD 50", "LD_D_B"},
    {"DD 51", "LD_D_C"},
    {"DD 52", "LD_D_D"},
    {"DD 53", "LD_D_E"},
    {"DD 54", "LD_D_IXh"},
    {"DD 55", "LD_D_IXl"},
    {"DD 56", "LD_D_ptr_IX_d"},
    {"DD 57", "LD_D_A"},
    {"DD 58", "LD_E_B"},
    {"DD 59", "LD_E_C"},
    {"DD 5A", "LD_E_D"},
    {"DD 5B", "LD_E_E"},
    {"DD 5C", "LD_E_IXh"},
    {"DD 5D", "LD_E_IXl"},
    {"DD 5E", "LD_E_ptr_IX_d"},
    {"DD 5F", "LD_E_A"},
    {"DD 60", "LD_IXh_B"},
    {"DD 61", "LD_IXh_C"},
    {"DD 62", "LD_IXh_D"},
    {"DD 63", "LD_IXh_E"},
    {"DD 64", "LD_IXh_IXh"},
    {"DD 65", "LD_IXh_IXl"},
    {"DD 66", "LD_H_ptr_IX_d"},
    {"DD 67", "LD_IXh_A"},
    {"DD 68", "LD_IXl_B"},
    {"DD 69", "LD_IXl_C"},
    {"DD 6A", "LD_IXl_D"},
    {"DD 6B", "LD_IXl_E"},
    {"DD 6C", "LD_IXl_IXh"},
    {"DD 6D", "LD_IXl_IXl"},
    {"DD 6E", "LD_L_ptr_IX_d"},
    {"DD 6F", "LD_IXl_A"},
    {"DD 70", "LD_ptr_IX_d_B"},
    {"DD 71", "LD_ptr_IX_d_C"},
    {"DD 72", "LD_ptr_IX_d_D"},
    {"DD 73", "LD_ptr_IX_d_E"},
    {"DD 74", "LD_ptr_IX_d_H"},
    {"DD 75", "LD_ptr_IX_d_L"},
    {"DD 76", "HALT"},
    {"DD 77", "LD_ptr_IX_d_A"},
    {"DD 78", "LD_A_B"},
    {"DD 79", "LD_A_C"},
    {"DD 7A", "LD_A_D"},
    {"DD 7B", "LD_A_E"},
    {"DD 7C", "LD_A_IXh"},
    {"DD 7D", "LD_A_IXl"},
    {"DD 7E", "LD_A_ptr_IX_d"},
    {"DD 7F", "LD_A_A"},
    {"DD 80", "ADD_A_B"},
    {"DD 81", "ADD_A_C"},
    {"DD 82", "ADD_A_D"},
    {"DD 83", "ADD_A_E"},
    {"DD 84", "ADD_A_IXh"},
    {"DD 85", "ADD_A_IXl"},
    {"DD 86", "ADD_A_ptr_IX_d"},
    {"DD 87", "ADD_A_A"},
    {"DD 88", "ADC_A_B"},
    {"DD 89", "ADC_A_C"},
    {"DD 8A", "ADC_A_D"},
    {"DD 8B", "ADC_A_E"},
    {"DD 8C", "ADC_A_IXh"},
    {"DD 8D", "ADC_A_IXl"},
    {"DD 8E", "ADC_A_ptr_IX_d"},
    {"DD 8F", "ADC_A_A"},
    {"DD 90", "SUB_B"},
    {"DD 91", "SUB_C"},
    {"DD 92", "SUB_D"},
    {"DD 93", "SUB_E"},
    {"DD 94", "SUB_IXh"},
    {"DD 95", "SUB_IXl"},
    {"DD 96", "SUB_ptr_IX_d"},
    {"DD 97", "SUB_A"},
    {"DD 98", "SBC_A_B"},
    {"DD 99", "SBC_A_C"},
    {"DD 9A", "SBC_A_D"},
    {"DD 9B", "SBC_A_E"},
    {"DD 9C", "SBC_A_IXh"},
    {"DD 9D", "SBC_A_IXl"},
    {"DD 9E", "SBC_A_ptr_IX_d"},
    {"DD 9F", "SBC_A_A"},
    {"DD A0", "AND_B"},
    {"DD A1", "AND_C"},
    {"DD A2", "AND_D"},
    {"DD A3", "AND_E"},
    {"DD A4", "AND_IXh"},
    {"DD A5", "AND_IXl"},
    {"DD A6", "AND_ptr_IX_d"},
    {"DD A7", "AND_A"},
    {"DD A8", "XOR_B"},
    {"DD A9", "XOR_C"},
    {"DD AA", "XOR_D"},
    {"DD AB", "XOR_E"},
    {"DD AC", "XOR_IXh"},
    {"DD AD", "XOR_IXl"},
    {"DD AE", "XOR_ptr_IX_d"},
    {"DD AF", "XOR_A"},
    {"DD B0", "OR_B"},
    {"DD B1", "OR_C"},
    {"DD B2", "OR_D"},
    {"DD B3", "OR_E"},
    {"DD B4", "OR_IXh"},
    {"DD B5", "OR_IXl"},
    {"DD B6", "OR_ptr_IX_d"},
    {"DD B7", "OR_A"},
    {"DD B8", "CP_B"},
    {"DD B9", "CP_C"},
    {"DD BA", "CP_D"},
    {"DD BB", "CP_E"},
    {"DD BC", "CP_IXh"},
    {"DD BD", "CP_IXl"},
    {"DD BE", "CP_ptr_IX_d"},
    {"DD BF", "CP_A"},
    {"DD C0", "RET_NZ"},
    {"DD C1", "POP_BC"},
    {"DD C2", "JP_NZ_nn"},
    {"DD C3", "JP_nn"},
    {"DD C4", "CALL_NZ_nn"},
    {"DD C5", "PUSH_BC"},
    {"DD C6", "ADD_A_n"},
    {"DD C7", "RST_0"},
    {"DD C8", "RET_Z"},
    {"DD C9", "RET"},
    {"DD CA", "JP_Z_nn"},
    {"DD CB", "_See_DDCB_info_"},
    {"DD CC", "CALL_Z_nn"},
    {"DD CD", "CALL_nn"},
    {"DD CE", "ADC_A_n"},
    {"DD CF", "RST_8"},
    {"DD D0", "RET_NC"},
    {"DD D1", "POP_DE"},
    {"DD D2", "JP_NC_nn"},
    {"DD D3", "OUT_ptr_n_A"},
    {"DD D4", "CALL_NC_nn"},
    {"DD D5", "PUSH_DE"},
    {"DD D6", "SUB_n"},
    {"DD D7", "RST_10H"},
    {"DD D8", "RET_C"},
    {"DD D9", "EXX"},
    {"DD DA", "JP_C_nn"},
    {"DD DB", "IN_A_ptr_n"},
    {"DD DC", "CALL_C_nn"},
    {"DD DD", "_IX_Prefix_"},
    {"DD DE", "SBC_A_n"},
    {"DD DF", "RST_18H"},
    {"DD E0", "RET_PO"},
    {"DD E1", "POP_IX"},
    {"DD E2", "JP_PO_nn"},
    {"DD E3", "EX_ptr_SP_IX"},
    {"DD E4", "CALL_PO_nn"},
    {"DD E5", "PUSH_IX"},
    {"DD E6", "AND_n"},
    {"DD E7", "RST_20H"},
    {"DD E8", "RET_PE"},
    {"DD E9", "JP_ptr_IX"},
    {"DD EA", "JP_PE_nn"},
    {"DD EB", "EX_DE_HL"},
    {"DD EC", "CALL_PE_nn"},
    {"DD ED", "_Prefix_"},
    {"DD EE", "XOR_n"},
    {"DD EF", "RST_28H"},
    {"DD F0", "RET_P"},
    {"DD F1", "POP_AF"},
    {"DD F2", "JP_P_nn"},
    {"DD F3", "DI"},
    {"DD F4", "CALL_P_nn"},
    {"DD F5", "PUSH_AF"},
    {"DD F6", "OR_n"},
    {"DD F7", "RST_30H"},
    {"DD F8", "RET_M"},
    {"DD F9", "LD_SP_IX"},
    {"DD FA", "JP_M_nn"},
    {"DD FB", "EI"},
    {"DD FC", "CALL_M_nn"},
    {"DD FD", "_IY_Prefix_"},
    {"DD FE", "CP_n"},
    {"DD FF", "RST_38H"},
}};

inline constexpr std::array<TestOpcodeInfo, 256> TestOpcodeTableED = {{
    {"ED 00", "NOP"},
    {"ED 01", "NOP"},
    {"ED 02", "NOP"},
    {"ED 03", "NOP"},
    {"ED 04", "NOP"},
    {"ED 05", "NOP"},
    {"ED 06", "NOP"},
    {"ED 07", "NOP"},
    {"ED 08", "NOP"},
    {"ED 09", "NOP"},
    {"ED 0A", "NOP"},
    {"ED 0B", "NOP"},
    {"ED 0C", "NOP"},
    {"ED 0D", "NOP"},
    {"ED 0E", "NOP"},
    {"ED 0F", "NOP"},
    {"ED 10", "NOP"},
    {"ED 11", "NOP"},
    {"ED 12", "NOP"},
    {"ED 13", "NOP"},
    {"ED 14", "NOP"},
    {"ED 15", "NOP"},
    {"ED 16", "NOP"},
    {"ED 17", "NOP"},
    {"ED 18", "NOP"},
    {"ED 19", "NOP"},
    {"ED 1A", "NOP"},
    {"ED 1B", "NOP"},
    {"ED 1C", "NOP"},
    {"ED 1D", "NOP"},
    {"ED 1E", "NOP"},
    {"ED 1F", "NOP"},
    {"ED 20", "NOP"},
    {"ED 21", "NOP"},
    {"ED 22", "NOP"},
    {"ED 23", "NOP"},
    {"ED 24", "NOP"},
    {"ED 25", "NOP"},
    {"ED 26", "NOP"},
    {"ED 27", "NOP"},
    {"ED 28", "NOP"},
    {"ED 29", "NOP"},
    {"ED 2A", "NOP"},
    {"ED 2B", "NOP"},
    {"ED 2C", "NOP"},
    {"ED 2D", "NOP"},
    {"ED 2E", "NOP"},
    {"ED 2F", "NOP"},
    {"ED 30", "NOP"},
    {"ED 31", "NOP"},
    {"ED 32", "NOP"},
    {"ED 33", "NOP"},
    {"ED 34", "NOP"},
    {"ED 35", "NOP"},
    {"ED 36", "NOP"},
    {"ED 37", "NOP"},
    {"ED 38", "NOP"},
    {"ED 39", "NOP"},
    {"ED 3A", "NOP"},
    {"ED 3B", "NOP"},
    {"ED 3C", "NOP"},
    {"ED 3D", "NOP"},
    {"ED 3E", "NOP"},
    {"ED 3F", "NOP"},
    {"ED 40", "IN_B_ptr_C"},
    {"ED 41", "OUT_ptr_C_B"},
    {"ED 42", "SBC_HL_BC"},
    {"ED 43", "LD_ptr_nn_BC"},
    {"ED 44", "NEG"},
    {"ED 45", "RETN"},
    {"ED 46", "IM_0"},
    {"ED 47", "LD_I_A"},
    {"ED 48", "IN_C_ptr_C"},
    {"ED 49", "OUT_ptr_C_C"},
    {"ED 4A", "ADC_HL_BC"},
    {"ED 4B", "LD_BC_ptr_nn"},
    {"ED 4C", "NEG"},
    {"ED 4D", "RETI"},
    {"ED 4E", "IM____0__"},
    {"ED 4F", "LD_R_A"},
    {"ED 50", "IN_D_ptr_C"},
    {"ED 51", "OUT_ptr_C_D"},
    {"ED 52", "SBC_HL_DE"},
    {"ED 53", "LD_ptr_nn_DE"},
    {"ED 54", "NEG"},
    {"ED 55", "RETN"},
    {"ED 56", "IM_1"},
    {"ED 57", "LD_A_I"},
    {"ED 58", "IN_E_ptr_C"},
    {"ED 59", "OUT_ptr_C_E"},
    {"ED 5A", "ADC_HL_DE"},
    {"ED 5B", "LD_DE_ptr_nn"},
    {"ED 5C", "NEG"},
    {"ED 5D", "RETI"},
    {"ED 5E", "IM_2"},
    {"ED 5F", "LD_A_R"},
    {"ED 60", "IN_H_ptr_C"},
    {"ED 61", "OUT_ptr_C_H"},
    {"ED 62", "SBC_HL_HL"},
    {"ED 63", "LD_ptr_nn_HL"},
    {"ED 64", "NEG"},
    {"ED 65", "RETN"},
    {"ED 66", "IM_0"},
    {"ED 67", "RRD"},
    {"ED 68", "IN_L_ptr_C"},
    {"ED 69", "OUT_ptr_C_L"},
    {"ED 6A", "ADC_HL_HL"},
    {"ED 6B", "LD_HL_ptr_nn"},
    {"ED 6C", "NEG"},
    {"ED 6D", "RETI"},
    {"ED 6E", "IM____0__"},
    {"ED 6F", "RLD"},
    {"ED 70", "IN_X_ptr_C"},
    {"ED 71", "OUT_ptr_C_Xptr_0"},
    {"ED 72", "SBC_HL_SP"},
    {"ED 73", "LD_ptr_nn_SP"},
    {"ED 74", "NEG"},
    {"ED 75", "RETN"},
    {"ED 76", "IM_1"},
    {"ED 77", "NOP"},
    {"ED 78", "IN_A_ptr_C"},
    {"ED 79", "OUT_ptr_C_A"},
    {"ED 7A", "ADC_HL_SP"},
    {"ED 7B", "LD_SP_ptr_nn"},
    {"ED 7C", "NEG"},
    {"ED 7D", "RETI"},
    {"ED 7E", "IM_2"},
    {"ED 7F", "NOP"},
    {"ED 80", "NOP"},
    {"ED 81", "NOP"},
    {"ED 82", "NOP"},
    {"ED 83", "NOP"},
    {"ED 84", "NOP"},
    {"ED 85", "NOP"},
    {"ED 86", "NOP"},
    {"ED 87", "NOP"},
    {"ED 88", "NOP"},
    {"ED 89", "NOP"},
    {"ED 8A", "NOP"},
    {"ED 8B", "NOP"},
    {"ED 8C", "NOP"},
    {"ED 8D", "NOP"},
    {"ED 8E", "NOP"},
    {"ED 8F", "NOP"},
    {"ED 90", "NOP"},
    {"ED 91", "NOP"},
    {"ED 92", "NOP"},
    {"ED 93", "NOP"},
    {"ED 94", "NOP"},
    {"ED 95", "NOP"},
    {"ED 96", "NOP"},
    {"ED 97", "NOP"},
    {"ED 98", "NOP"},
    {"ED 99", "NOP"},
    {"ED 9A", "NOP"},
    {"ED 9B", "NOP"},
    {"ED 9C", "NOP"},
    {"ED 9D", "NOP"},
    {"ED 9E", "NOP"},
    {"ED 9F", "NOP"},
    {"ED A0", "LDI"},
    {"ED A1", "CPI"},
    {"ED A2", "INI"},
    {"ED A3", "OUTI"},
    {"ED A4", "NOP"},
    {"ED A5", "NOP"},
    {"ED A6", "NOP"},
    {"ED A7", "NOP"},
    {"ED A8", "LDD"},
    {"ED A9", "CPD"},
    {"ED AA", "IND"},
    {"ED AB", "OUTD"},
    {"ED AC", "NOP"},
    {"ED AD", "NOP"},
    {"ED AE", "NOP"},
    {"ED AF", "NOP"},
    {"ED B0", "LDIR"},
    {"ED B1", "CPIR"},
    {"ED B2", "INIR"},
    {"ED B3", "OTIR"},
    {"ED B4", "NOP"},
    {"ED B5", "NOP"},
    {"ED B6", "NOP"},
    {"ED B7", "NOP"},
    {"ED B8", "LDDR"},
    {"ED B9", "CPDR"},
    {"ED BA", "INDR"},
    {"ED BB", "OTDR"},
    {"ED BC", "NOP"},
    {"ED BD", "NOP"},
    {"ED BE", "NOP"},
    {"ED BF", "NOP"},
    {"ED C0", "NOP"},
    {"ED C1", "NOP"},
    {"ED C2", "NOP"},
    {"ED C3", "NOP"},
    {"ED C4", "NOP"},
    {"ED C5", "NOP"},
    {"ED C6", "NOP"},
    {"ED C7", "NOP"},
    {"ED C8", "NOP"},
    {"ED C9", "NOP"},
    {"ED CA", "NOP"},
    {"ED CB", "NOP"},
    {"ED CC", "NOP"},
    {"ED CD", "NOP"},
    {"ED CE", "NOP"},
    {"ED CF", "NOP"},
    {"ED D0", "NOP"},
    {"ED D1", "NOP"},
    {"ED D2", "NOP"},
    {"ED D3", "NOP"},
    {"ED D4", "NOP"},
    {"ED D5", "NOP"},
    {"ED D6", "NOP"},
    {"ED D7", "NOP"},
    {"ED D8", "NOP"},
    {"ED D9", "NOP"},
    {"ED DA", "NOP"},
    {"ED DB", "NOP"},
    {"ED DC", "NOP"},
    {"ED DD", "NOP"},
    {"ED DE", "NOP"},
    {"ED DF", "NOP"},
    {"ED E0", "NOP"},
    {"ED E1", "NOP"},
    {"ED E2", "NOP"},
    {"ED E3", "NOP"},
    {"ED E4", "NOP"},
    {"ED E5", "NOP"},
    {"ED E6", "NOP"},
    {"ED E7", "NOP"},
    {"ED E8", "NOP"},
    {"ED E9", "NOP"},
    {"ED EA", "NOP"},
    {"ED EB", "NOP"},
    {"ED EC", "NOP"},
    {"ED ED", "NOP"},
    {"ED EE", "NOP"},
    {"ED EF", "NOP"},
    {"ED F0", "NOP"},
    {"ED F1", "NOP"},
    {"ED F2", "NOP"},
    {"ED F3", "NOP"},
    {"ED F4", "NOP"},
    {"ED F5", "NOP"},
    {"ED F6", "NOP"},
    {"ED F7", "NOP"},
    {"ED F8", "NOP"},
    {"ED F9", "NOP"},
    {"ED FA", "NOP"},
    {"ED FB", "NOP"},
    {"ED FC", "NOP"},
    {"ED FD", "NOP"},
    {"ED FE", "NOP"},
    {"ED FF", "NOP"},
}};

inline constexpr std::array<TestOpcodeInfo, 256> TestOpcodeTableFD = {{
    {"FD 00", "NOP"},
    {"FD 01", "LD_BC_nn"},
    {"FD 02", "LD_ptr_BC_A"},
    {"FD 03", "INC_BC"},
    {"FD 04", "INC_B"},
    {"FD 05", "DEC_B"},
    {"FD 06", "LD_B_n"},
    {"FD 07", "RLCA"},
    {"FD 08", "EX_AF_AF_"},
    {"FD 09", "ADD_IY_BC"},
    {"FD 0A", "LD_A_ptr_BC"},
    {"FD 0B", "DEC_BC"},
    {"FD 0C", "INC_C"},
    {"FD 0D", "DEC_C"},
    {"FD 0E", "LD_C_n"},
    {"FD 0F", "RRCA"},
    {"FD 10", "DJNZ_d"},
    {"FD 11", "LD_DE_nn"},
    {"FD 12", "LD_ptr_DE_A"},
    {"FD 13", "INC_DE"},
    {"FD 14", "INC_D"},
    {"FD 15", "DEC_D"},
    {"FD 16", "LD_D_n"},
    {"FD 17", "RLA"},
    {"FD 18", "JR_d"},
    {"FD 19", "ADD_IY_DE"},
    {"FD 1A", "LD_A_ptr_DE"},
    {"FD 1B", "DEC_DE"},
    {"FD 1C", "INC_E"},
    {"FD 1D", "DEC_E"},
    {"FD 1E", "LD_E_n"},
    {"FD 1F", "RRA"},
    {"FD 20", "JR_NZ_d"},
    {"FD 21", "LD_IY_nn"},
    {"FD 22", "LD_ptr_nn_IY"},
    {"FD 23", "INC_IY"},
    {"FD 24", "INC_IYh"},
    {"FD 25", "DEC_IYh"},
    {"FD 26", "LD_IYh_n"},
    {"FD 27", "DAA"},
    {"FD 28", "JR_Z_d"},
    {"FD 29", "ADD_IY_IY"},
    {"FD 2A", "LD_IY_ptr_nn"},
    {"FD 2B", "DEC_IY"},
    {"FD 2C", "INC_IYl"},
    {"FD 2D", "DEC_IYl"},
    {"FD 2E", "LD_IYl_n"},
    {"FD 2F", "CPL"},
    {"FD 30", "JR_NC_d"},
    {"FD 31", "LD_SP_nn"},
    {"FD 32", "LD_ptr_nn_A"},
    {"FD 33", "INC_SP"},
    {"FD 34", "INC_ptr_IY_d"},
    {"FD 35", "DEC_ptr_IY_d"},
    {"FD 36", "LD_ptr_IY_d_n"},
    {"FD 37", "SCF"},
    {"FD 38", "JR_C_d"},
    {"FD 39", "ADD_IY_SP"},
    {"FD 3A", "LD_A_ptr_nn"},
    {"FD 3B", "DEC_SP"},
    {"FD 3C", "INC_A"},
    {"FD 3D", "DEC_A"},
    {"FD 3E", "LD_A_n"},
    {"FD 3F", "CCF"},
    {"FD 40", "LD_B_B"},
    {"FD 41", "LD_B_C"},
    {"FD 42", "LD_B_D"},
    {"FD 43", "LD_B_E"},
    {"FD 44", "LD_B_IYh"},
    {"FD 45", "LD_B_IYl"},
    {"FD 46", "LD_B_ptr_IY_d"},
    {"FD 47", "LD_B_A"},
    {"FD 48", "LD_C_B"},
    {"FD 49", "LD_C_C"},
    {"FD 4A", "LD_C_D"},
    {"FD 4B", "LD_C_E"},
    {"FD 4C", "LD_C_IYh"},
    {"FD 4D", "LD_C_IYl"},
    {"FD 4E", "LD_C_ptr_IY_d"},
    {"FD 4F", "LD_C_A"},
    {"FD 50", "LD_D_B"},
    {"FD 51", "LD_D_C"},
    {"FD 52", "LD_D_D"},
    {"FD 53", "LD_D_E"},
    {"FD 54", "LD_D_IYh"},
    {"FD 55", "LD_D_IYl"},
    {"FD 56", "LD_D_ptr_IY_d"},
    {"FD 57", "LD_D_A"},
    {"FD 58", "LD_E_B"},
    {"FD 59", "LD_E_C"},
    {"FD 5A", "LD_E_D"},
    {"FD 5B", "LD_E_E"},
    {"FD 5C", "LD_E_IYh"},
    {"FD 5D", "LD_E_IYl"},
    {"FD 5E", "LD_E_ptr_IY_d"},
    {"FD 5F", "LD_E_A"},
    {"FD 60", "LD_IYh_B"},
    {"FD 61", "LD_IYh_C"},
    {"FD 62", "LD_IYh_D"},
    {"FD 63", "LD_IYh_E"},
    {"FD 64", "LD_IYh_IYh"},
    {"FD 65", "LD_IYh_IYl"},
    {"FD 66", "LD_H_ptr_IY_d"},
    {"FD 67", "LD_IYh_A"},
    {"FD 68", "LD_IYl_B"},
    {"FD 69", "LD_IYl_C"},
    {"FD 6A", "LD_IYl_D"},
    {"FD 6B", "LD_IYl_E"},
    {"FD 6C", "LD_IYl_IYh"},
    {"FD 6D", "LD_IYl_IYl"},
    {"FD 6E", "LD_L_ptr_IY_d"},
    {"FD 6F", "LD_IYl_A"},
    {"FD 70", "LD_ptr_IY_d_B"},
    {"FD 71", "LD_ptr_IY_d_C"},
    {"FD 72", "LD_ptr_IY_d_D"},
    {"FD 73", "LD_ptr_IY_d_E"},
    {"FD 74", "LD_ptr_IY_d_H"},
    {"FD 75", "LD_ptr_IY_d_L"},
    {"FD 76", "HALT"},
    {"FD 77", "LD_ptr_IY_d_A"},
    {"FD 78", "LD_A_B"},
    {"FD 79", "LD_A_C"},
    {"FD 7A", "LD_A_D"},
    {"FD 7B", "LD_A_E"},
    {"FD 7C", "LD_A_IYh"},
    {"FD 7D", "LD_A_IYl"},
    {"FD 7E", "LD_A_ptr_IY_d"},
    {"FD 7F", "LD_A_A"},
    {"FD 80", "ADD_A_B"},
    {"FD 81", "ADD_A_C"},
    {"FD 82", "ADD_A_D"},
    {"FD 83", "ADD_A_E"},
    {"FD 84", "ADD_A_IYh"},
    {"FD 85", "ADD_A_IYl"},
    {"FD 86", "ADD_A_ptr_IY_d"},
    {"FD 87", "ADD_A_A"},
    {"FD 88", "ADC_A_B"},
    {"FD 89", "ADC_A_C"},
    {"FD 8A", "ADC_A_D"},
    {"FD 8B", "ADC_A_E"},
    {"FD 8C", "ADC_A_IYh"},
    {"FD 8D", "ADC_A_IYl"},
    {"FD 8E", "ADC_A_ptr_IY_d"},
    {"FD 8F", "ADC_A_A"},
    {"FD 90", "SUB_B"},
    {"FD 91", "SUB_C"},
    {"FD 92", "SUB_D"},
    {"FD 93", "SUB_E"},
    {"FD 94", "SUB_IYh"},
    {"FD 95", "SUB_IYl"},
    {"FD 96", "SUB_ptr_IY_d"},
    {"FD 97", "SUB_A"},
    {"FD 98", "SBC_A_B"},
    {"FD 99", "SBC_A_C"},
    {"FD 9A", "SBC_A_D"},
    {"FD 9B", "SBC_A_E"},
    {"FD 9C", "SBC_A_IYh"},
    {"FD 9D", "SBC_A_IYl"},
    {"FD 9E", "SBC_A_ptr_IY_d"},
    {"FD 9F", "SBC_A_A"},
    {"FD A0", "AND_B"},
    {"FD A1", "AND_C"},
    {"FD A2", "AND_D"},
    {"FD A3", "AND_E"},
    {"FD A4", "AND_IYh"},
    {"FD A5", "AND_IYl"},
    {"FD A6", "AND_ptr_IY_d"},
    {"FD A7", "AND_A"},
    {"FD A8", "XOR_B"},
    {"FD A9", "XOR_C"},
    {"FD AA", "XOR_D"},
    {"FD AB", "XOR_E"},
    {"FD AC", "XOR_IYh"},
    {"FD AD", "XOR_IYl"},
    {"FD AE", "XOR_ptr_IY_d"},
    {"FD AF", "XOR_A"},
    {"FD B0", "OR_B"},
    {"FD B1", "OR_C"},
    {"FD B2", "OR_D"},
    {"FD B3", "OR_E"},
    {"FD B4", "OR_IYh"},
    {"FD B5", "OR_IYl"},
    {"FD B6", "OR_ptr_IY_d"},
    {"FD B7", "OR_A"},
    {"FD B8", "CP_B"},
    {"FD B9", "CP_C"},
    {"FD BA", "CP_D"},
    {"FD BB", "CP_E"},
    {"FD BC", "CP_IYh"},
    {"FD BD", "CP_IYl"},
    {"FD BE", "CP_ptr_IY_d"},
    {"FD BF", "CP_A"},
    {"FD C0", "RET_NZ"},
    {"FD C1", "POP_BC"},
    {"FD C2", "JP_NZ_nn"},
    {"FD C3", "JP_nn"},
    {"FD C4", "CALL_NZ_nn"},
    {"FD C5", "PUSH_BC"},
    {"FD C6", "ADD_A_n"},
    {"FD C7", "RST_0"},
    {"FD C8", "RET_Z"},
    {"FD C9", "RET"},
    {"FD CA", "JP_Z_nn"},
    {"FD CB", "_See_DDCB_info_"},
    {"FD CC", "CALL_Z_nn"},
    {"FD CD", "CALL_nn"},
    {"FD CE", "ADC_A_n"},
    {"FD CF", "RST_8"},
    {"FD D0", "RET_NC"},
    {"FD D1", "POP_DE"},
    {"FD D2", "JP_NC_nn"},
    {"FD D3", "OUT_ptr_n_A"},
    {"FD D4", "CALL_NC_nn"},
    {"FD D5", "PUSH_DE"},
    {"FD D6", "SUB_n"},
    {"FD D7", "RST_10H"},
    {"FD D8", "RET_C"},
    {"FD D9", "EXX"},
    {"FD DA", "JP_C_nn"},
    {"FD DB", "IN_A_ptr_n"},
    {"FD DC", "CALL_C_nn"},
    {"FD DD", "_IY_Prefix_"},
    {"FD DE", "SBC_A_n"},
    {"FD DF", "RST_18H"},
    {"FD E0", "RET_PO"},
    {"FD E1", "POP_IY"},
    {"FD E2", "JP_PO_nn"},
    {"FD E3", "EX_ptr_SP_IY"},
    {"FD E4", "CALL_PO_nn"},
    {"FD E5", "PUSH_IY"},
    {"FD E6", "AND_n"},
    {"FD E7", "RST_20H"},
    {"FD E8", "RET_PE"},
    {"FD E9", "JP_ptr_IY"},
    {"FD EA", "JP_PE_nn"},
    {"FD EB", "EX_DE_HL"},
    {"FD EC", "CALL_PE_nn"},
    {"FD ED", "_Prefix_"},
    {"FD EE", "XOR_n"},
    {"FD EF", "RST_28H"},
    {"FD F0", "RET_P"},
    {"FD F1", "POP_AF"},
    {"FD F2", "JP_P_nn"},
    {"FD F3", "DI"},
    {"FD F4", "CALL_P_nn"},
    {"FD F5", "PUSH_AF"},
    {"FD F6", "OR_n"},
    {"FD F7", "RST_30H"},
    {"FD F8", "RET_M"},
    {"FD F9", "LD_SP_IY"},
    {"FD FA", "JP_M_nn"},
    {"FD FB", "EI"},
    {"FD FC", "CALL_M_nn"},
    {"FD FD", "_IY_Prefix_"},
    {"FD FE", "CP_n"},
    {"FD FF", "RST_38H"},
}};

inline constexpr std::array<TestOpcodeInfo, 256> TestOpcodeTableDDCB = {{
    {"FD CB __ 00", "LD_B_RLC_ptr_IX_d"},
    {"FD CB __ 01", "LD_C_RLC_ptr_IX_d"},
    {"FD CB __ 02", "LD_D_RLC_ptr_IX_d"},
    {"FD CB __ 03", "LD_E_RLC_ptr_IX_d"},
    {"FD CB __ 04", "LD_H_RLC_ptr_IX_d"},
    {"FD CB __ 05", "LD_L_RLC_ptr_IX_d"},
    {"FD CB __ 06", "RLC_ptr_IX_d"},
    {"FD CB __ 07", "LD_A_RLC_ptr_IX_d"},
    {"FD CB __ 08", "LD_B_RRC_ptr_IX_d"},
    {"FD CB __ 09", "LD_C_RRC_ptr_IX_d"},
    {"FD CB __ 0A", "LD_D_RRC_ptr_IX_d"},
    {"FD CB __ 0B", "LD_E_RRC_ptr_IX_d"},
    {"FD CB __ 0C", "LD_H_RRC_ptr_IX_d"},
    {"FD CB __ 0D", "LD_L_RRC_ptr_IX_d"},
    {"FD CB __ 0E", "RRC_ptr_IX_d"},
    {"FD CB __ 0F", "LD_A_RRC_ptr_IX_d"},
    {"FD CB __ 10", "LD_B_RL_ptr_IX_d"},
    {"FD CB __ 11", "LD_C_RL_ptr_IX_d"},
    {"FD CB __ 12", "LD_D_RL_ptr_IX_d"},
    {"FD CB __ 13", "LD_E_RL_ptr_IX_d"},
    {"FD CB __ 14", "LD_H_RL_ptr_IX_d"},
    {"FD CB __ 15", "LD_L_RL_ptr_IX_d"},
    {"FD CB __ 16", "RL_ptr_IX_d"},
    {"FD CB __ 17", "LD_A_RL_ptr_IX_d"},
    {"FD CB __ 18", "LD_B_RR_ptr_IX_d"},
    {"FD CB __ 19", "LD_C_RR_ptr_IX_d"},
    {"FD CB __ 1A", "LD_D_RR_ptr_IX_d"},
    {"FD CB __ 1B", "LD_E_RR_ptr_IX_d"},
    {"FD CB __ 1C", "LD_H_RR_ptr_IX_d"},
    {"FD CB __ 1D", "LD_L_RR_ptr_IX_d"},
    {"FD CB __ 1E", "RR_ptr_IX_d"},
    {"FD CB __ 1F", "LD_A_RR_ptr_IX_d"},
    {"FD CB __ 20", "LD_B_SLA_ptr_IX_d"},
    {"FD CB __ 21", "LD_C_SLA_ptr_IX_d"},
    {"FD CB __ 22", "LD_D_SLA_ptr_IX_d"},
    {"FD CB __ 23", "LD_E_SLA_ptr_IX_d"},
    {"FD CB __ 24", "LD_H_SLA_ptr_IX_d"},
    {"FD CB __ 25", "LD_L_SLA_ptr_IX_d"},
    {"FD CB __ 26", "SLA_ptr_IX_d"},
    {"FD CB __ 27", "LD_A_SLA_ptr_IX_d"},
    {"FD CB __ 28", "LD_B_SRA_ptr_IX_d"},
    {"FD CB __ 29", "LD_C_SRA_ptr_IX_d"},
    {"FD CB __ 2A", "LD_D_SRA_ptr_IX_d"},
    {"FD CB __ 2B", "LD_E_SRA_ptr_IX_d"},
    {"FD CB __ 2C", "LD_H_SRA_ptr_IX_d"},
    {"FD CB __ 2D", "LD_L_SRA_ptr_IX_d"},
    {"FD CB __ 2E", "SRA_ptr_IX_d"},
    {"FD CB __ 2F", "LD_A_SRA_ptr_IX_d"},
    {"FD CB __ 30", "LD_B_SLL_ptr_IX_d"},
    {"FD CB __ 31", "LD_C_SLL_ptr_IX_d"},
    {"FD CB __ 32", "LD_D_SLL_ptr_IX_d"},
    {"FD CB __ 33", "LD_E_SLL_ptr_IX_d"},
    {"FD CB __ 34", "LD_H_SLL_ptr_IX_d"},
    {"FD CB __ 35", "LD_L_SLL_ptr_IX_d"},
    {"FD CB __ 36", "SLL_ptr_IX_d"},
    {"FD CB __ 37", "LD_A_SLL_ptr_IX_d"},
    {"FD CB __ 38", "LD_B_SRL_ptr_IX_d"},
    {"FD CB __ 39", "LD_C_SRL_ptr_IX_d"},
    {"FD CB __ 3A", "LD_D_SRL_ptr_IX_d"},
    {"FD CB __ 3B", "LD_E_SRL_ptr_IX_d"},
    {"FD CB __ 3C", "LD_H_SRL_ptr_IX_d"},
    {"FD CB __ 3D", "LD_L_SRL_ptr_IX_d"},
    {"FD CB __ 3E", "SRL_ptr_IX_d"},
    {"FD CB __ 3F", "LD_A_SRL_ptr_IX_d"},
    {"FD CB __ 40", "BIT_0_ptr_IX_d"},
    {"FD CB __ 41", "BIT_0_ptr_IX_d"},
    {"FD CB __ 42", "BIT_0_ptr_IX_d"},
    {"FD CB __ 43", "BIT_0_ptr_IX_d"},
    {"FD CB __ 44", "BIT_0_ptr_IX_d"},
    {"FD CB __ 45", "BIT_0_ptr_IX_d"},
    {"FD CB __ 46", "BIT_0_ptr_IX_d"},
    {"FD CB __ 47", "BIT_0_ptr_IX_d"},
    {"FD CB __ 48", "BIT_1_ptr_IX_d"},
    {"FD CB __ 49", "BIT_1_ptr_IX_d"},
    {"FD CB __ 4A", "BIT_1_ptr_IX_d"},
    {"FD CB __ 4B", "BIT_1_ptr_IX_d"},
    {"FD CB __ 4C", "BIT_1_ptr_IX_d"},
    {"FD CB __ 4D", "BIT_1_ptr_IX_d"},
    {"FD CB __ 4E", "BIT_1_ptr_IX_d"},
    {"FD CB __ 4F", "BIT_1_ptr_IX_d"},
    {"FD CB __ 50", "BIT_2_ptr_IX_d"},
    {"FD CB __ 51", "BIT_2_ptr_IX_d"},
    {"FD CB __ 52", "BIT_2_ptr_IX_d"},
    {"FD CB __ 53", "BIT_2_ptr_IX_d"},
    {"FD CB __ 54", "BIT_2_ptr_IX_d"},
    {"FD CB __ 55", "BIT_2_ptr_IX_d"},
    {"FD CB __ 56", "BIT_2_ptr_IX_d"},
    {"FD CB __ 57", "BIT_2_ptr_IX_d"},
    {"FD CB __ 58", "BIT_3_ptr_IX_d"},
    {"FD CB __ 59", "BIT_3_ptr_IX_d"},
    {"FD CB __ 5A", "BIT_3_ptr_IX_d"},
    {"FD CB __ 5B", "BIT_3_ptr_IX_d"},
    {"FD CB __ 5C", "BIT_3_ptr_IX_d"},
    {"FD CB __ 5D", "BIT_3_ptr_IX_d"},
    {"FD CB __ 5E", "BIT_3_ptr_IX_d"},
    {"FD CB __ 5F", "BIT_3_ptr_IX_d"},
    {"FD CB __ 60", "BIT_4_ptr_IX_d"},
    {"FD CB __ 61", "BIT_4_ptr_IX_d"},
    {"FD CB __ 62", "BIT_4_ptr_IX_d"},
    {"FD CB __ 63", "BIT_4_ptr_IX_d"},
    {"FD CB __ 64", "BIT_4_ptr_IX_d"},
    {"FD CB __ 65", "BIT_4_ptr_IX_d"},
    {"FD CB __ 66", "BIT_4_ptr_IX_d"},
    {"FD CB __ 67", "BIT_4_ptr_IX_d"},
    {"FD CB __ 68", "BIT_5_ptr_IX_d"},
    {"FD CB __ 69", "BIT_5_ptr_IX_d"},
    {"FD CB __ 6A", "BIT_5_ptr_IX_d"},
    {"FD CB __ 6B", "BIT_5_ptr_IX_d"},
    {"FD CB __ 6C", "BIT_5_ptr_IX_d"},
    {"FD CB __ 6D", "BIT_5_ptr_IX_d"},
    {"FD CB __ 6E", "BIT_5_ptr_IX_d"},
    {"FD CB __ 6F", "BIT_5_ptr_IX_d"},
    {"FD CB __ 70", "BIT_6_ptr_IX_d"},
    {"FD CB __ 71", "BIT_6_ptr_IX_d"},
    {"FD CB __ 72", "BIT_6_ptr_IX_d"},
    {"FD CB __ 73", "BIT_6_ptr_IX_d"},
    {"FD CB __ 74", "BIT_6_ptr_IX_d"},
    {"FD CB __ 75", "BIT_6_ptr_IX_d"},
    {"FD CB __ 76", "BIT_6_ptr_IX_d"},
    {"FD CB __ 77", "BIT_6_ptr_IX_d"},
    {"FD CB __ 78", "BIT_7_ptr_IX_d"},
    {"FD CB __ 79", "BIT_7_ptr_IX_d"},
    {"FD CB __ 7A", "BIT_7_ptr_IX_d"},
    {"FD CB __ 7B", "BIT_7_ptr_IX_d"},
    {"FD CB __ 7C", "BIT_7_ptr_IX_d"},
    {"FD CB __ 7D", "BIT_7_ptr_IX_d"},
    {"FD CB __ 7E", "BIT_7_ptr_IX_d"},
    {"FD CB __ 7F", "BIT_7_ptr_IX_d"},
    {"FD CB __ 80", "LD_B_RES_0_ptr_IX_d"},
    {"FD CB __ 81", "LD_C_RES_0_ptr_IX_d"},
    {"FD CB __ 82", "LD_D_RES_0_ptr_IX_d"},
    {"FD CB __ 83", "LD_E_RES_0_ptr_IX_d"},
    {"FD CB __ 84", "LD_H_RES_0_ptr_IX_d"},
    {"FD CB __ 85", "LD_L_RES_0_ptr_IX_d"},
    {"FD CB __ 86", "RES_0_ptr_IX_d"},
    {"FD CB __ 87", "LD_A_RES_0_ptr_IX_d"},
    {"FD CB __ 88", "LD_B_RES_1_ptr_IX_d"},
    {"FD CB __ 89", "LD_C_RES_1_ptr_IX_d"},
    {"FD CB __ 8A", "LD_D_RES_1_ptr_IX_d"},
    {"FD CB __ 8B", "LD_E_RES_1_ptr_IX_d"},
    {"FD CB __ 8C", "LD_H_RES_1_ptr_IX_d"},
    {"FD CB __ 8D", "LD_L_RES_1_ptr_IX_d"},
    {"FD CB __ 8E", "RES_1_ptr_IX_d"},
    {"FD CB __ 8F", "LD_A_RES_1_ptr_IX_d"},
    {"FD CB __ 90", "LD_B_RES_2_ptr_IX_d"},
    {"FD CB __ 91", "LD_C_RES_2_ptr_IX_d"},
    {"FD CB __ 92", "LD_D_RES_2_ptr_IX_d"},
    {"FD CB __ 93", "LD_E_RES_2_ptr_IX_d"},
    {"FD CB __ 94", "LD_H_RES_2_ptr_IX_d"},
    {"FD CB __ 95", "LD_L_RES_2_ptr_IX_d"},
    {"FD CB __ 96", "RES_2_ptr_IX_d"},
    {"FD CB __ 97", "LD_A_RES_2_ptr_IX_d"},
    {"FD CB __ 98", "LD_B_RES_3_ptr_IX_d"},
    {"FD CB __ 99", "LD_C_RES_3_ptr_IX_d"},
    {"FD CB __ 9A", "LD_D_RES_3_ptr_IX_d"},
    {"FD CB __ 9B", "LD_E_RES_3_ptr_IX_d"},
    {"FD CB __ 9C", "LD_H_RES_3_ptr_IX_d"},
    {"FD CB __ 9D", "LD_L_RES_3_ptr_IX_d"},
    {"FD CB __ 9E", "RES_3_ptr_IX_d"},
    {"FD CB __ 9F", "LD_A_RES_3_ptr_IX_d"},
    {"FD CB __ A0", "LD_B_RES_4_ptr_IX_d"},
    {"FD CB __ A1", "LD_C_RES_4_ptr_IX_d"},
    {"FD CB __ A2", "LD_D_RES_4_ptr_IX_d"},
    {"FD CB __ A3", "LD_E_RES_4_ptr_IX_d"},
    {"FD CB __ A4", "LD_H_RES_4_ptr_IX_d"},
    {"FD CB __ A5", "LD_L_RES_4_ptr_IX_d"},
    {"FD CB __ A6", "RES_4_ptr_IX_d"},
    {"FD CB __ A7", "LD_A_RES_4_ptr_IX_d"},
    {"FD CB __ A8", "LD_B_RES_5_ptr_IX_d"},
    {"FD CB __ A9", "LD_C_RES_5_ptr_IX_d"},
    {"FD CB __ AA", "LD_D_RES_5_ptr_IX_d"},
    {"FD CB __ AB", "LD_E_RES_5_ptr_IX_d"},
    {"FD CB __ AC", "LD_H_RES_5_ptr_IX_d"},
    {"FD CB __ AD", "LD_L_RES_5_ptr_IX_d"},
    {"FD CB __ AE", "RES_5_ptr_IX_d"},
    {"FD CB __ AF", "LD_A_RES_5_ptr_IX_d"},
    {"FD CB __ B0", "LD_B_RES_6_ptr_IX_d"},
    {"FD CB __ B1", "LD_C_RES_6_ptr_IX_d"},
    {"FD CB __ B2", "LD_D_RES_6_ptr_IX_d"},
    {"FD CB __ B3", "LD_E_RES_6_ptr_IX_d"},
    {"FD CB __ B4", "LD_H_RES_6_ptr_IX_d"},
    {"FD CB __ B5", "LD_L_RES_6_ptr_IX_d"},
    {"FD CB __ B6", "RES_6_ptr_IX_d"},
    {"FD CB __ B7", "LD_A_RES_6_ptr_IX_d"},
    {"FD CB __ B8", "LD_B_RES_7_ptr_IX_d"},
    {"FD CB __ B9", "LD_C_RES_7_ptr_IX_d"},
    {"FD CB __ BA", "LD_D_RES_7_ptr_IX_d"},
    {"FD CB __ BB", "LD_E_RES_7_ptr_IX_d"},
    {"FD CB __ BC", "LD_H_RES_7_ptr_IX_d"},
    {"FD CB __ BD", "LD_L_RES_7_ptr_IX_d"},
    {"FD CB __ BE", "RES_7_ptr_IX_d"},
    {"FD CB __ BF", "LD_A_RES_7_ptr_IX_d"},
    {"FD CB __ C0", "LD_B_SET_0_ptr_IX_d"},
    {"FD CB __ C1", "LD_C_SET_0_ptr_IX_d"},
    {"FD CB __ C2", "LD_D_SET_0_ptr_IX_d"},
    {"FD CB __ C3", "LD_E_SET_0_ptr_IX_d"},
    {"FD CB __ C4", "LD_H_SET_0_ptr_IX_d"},
    {"FD CB __ C5", "LD_L_SET_0_ptr_IX_d"},
    {"FD CB __ C6", "SET_0_ptr_IX_d"},
    {"FD CB __ C7", "LD_A_SET_0_ptr_IX_d"},
    {"FD CB __ C8", "LD_B_SET_1_ptr_IX_d"},
    {"FD CB __ C9", "LD_C_SET_1_ptr_IX_d"},
    {"FD CB __ CA", "LD_D_SET_1_ptr_IX_d"},
    {"FD CB __ CB", "LD_E_SET_1_ptr_IX_d"},
    {"FD CB __ CC", "LD_H_SET_1_ptr_IX_d"},
    {"FD CB __ CD", "LD_L_SET_1_ptr_IX_d"},
    {"FD CB __ CE", "SET_1_ptr_IX_d"},
    {"FD CB __ CF", "LD_A_SET_1_ptr_IX_d"},
    {"FD CB __ D0", "LD_B_SET_2_ptr_IX_d"},
    {"FD CB __ D1", "LD_C_SET_2_ptr_IX_d"},
    {"FD CB __ D2", "LD_D_SET_2_ptr_IX_d"},
    {"FD CB __ D3", "LD_E_SET_2_ptr_IX_d"},
    {"FD CB __ D4", "LD_H_SET_2_ptr_IX_d"},
    {"FD CB __ D5", "LD_L_SET_2_ptr_IX_d"},
    {"FD CB __ D6", "SET_2_ptr_IX_d"},
    {"FD CB __ D7", "LD_A_SET_2_ptr_IX_d"},
    {"FD CB __ D8", "LD_B_SET_3_ptr_IX_d"},
    {"FD CB __ D9", "LD_C_SET_3_ptr_IX_d"},
    {"FD CB __ DA", "LD_D_SET_3_ptr_IX_d"},
    {"FD CB __ DB", "LD_E_SET_3_ptr_IX_d"},
    {"FD CB __ DC", "LD_H_SET_3_ptr_IX_d"},
    {"FD CB __ DD", "LD_L_SET_3_ptr_IX_d"},
    {"FD CB __ DE", "SET_3_ptr_IX_d"},
    {"FD CB __ DF", "LD_A_SET_3_ptr_IX_d"},
    {"FD CB __ E0", "LD_B_SET_4_ptr_IX_d"},
    {"FD CB __ E1", "LD_C_SET_4_ptr_IX_d"},
    {"FD CB __ E2", "LD_D_SET_4_ptr_IX_d"},
    {"FD CB __ E3", "LD_E_SET_4_ptr_IX_d"},
    {"FD CB __ E4", "LD_H_SET_4_ptr_IX_d"},
    {"FD CB __ E5", "LD_L_SET_4_ptr_IX_d"},
    {"FD CB __ E6", "SET_4_ptr_IX_d"},
    {"FD CB __ E7", "LD_A_SET_4_ptr_IX_d"},
    {"FD CB __ E8", "LD_B_SET_5_ptr_IX_d"},
    {"FD CB __ E9", "LD_C_SET_5_ptr_IX_d"},
    {"FD CB __ EA", "LD_D_SET_5_ptr_IX_d"},
    {"FD CB __ EB", "LD_E_SET_5_ptr_IX_d"},
    {"FD CB __ EC", "LD_H_SET_5_ptr_IX_d"},
    {"FD CB __ ED", "LD_L_SET_5_ptr_IX_d"},
    {"FD CB __ EE", "SET_5_ptr_IX_d"},
    {"FD CB __ EF", "LD_A_SET_5_ptr_IX_d"},
    {"FD CB __ F0", "LD_B_SET_6_ptr_IX_d"},
    {"FD CB __ F1", "LD_C_SET_6_ptr_IX_d"},
    {"FD CB __ F2", "LD_D_SET_6_ptr_IX_d"},
    {"FD CB __ F3", "LD_E_SET_6_ptr_IX_d"},
    {"FD CB __ F4", "LD_H_SET_6_ptr_IX_d"},
    {"FD CB __ F5", "LD_L_SET_6_ptr_IX_d"},
    {"FD CB __ F6", "SET_6_ptr_IX_d"},
    {"FD CB __ F7", "LD_A_SET_6_ptr_IX_d"},
    {"FD CB __ F8", "LD_B_SET_7_ptr_IX_d"},
    {"FD CB __ F9", "LD_C_SET_7_ptr_IX_d"},
    {"FD CB __ FA", "LD_D_SET_7_ptr_IX_d"},
    {"FD CB __ FB", "LD_E_SET_7_ptr_IX_d"},
    {"FD CB __ FC", "LD_H_SET_7_ptr_IX_d"},
    {"FD CB __ FD", "LD_L_SET_7_ptr_IX_d"},
    {"FD CB __ FE", "SET_7_ptr_IX_d"},
    {"FD CB __ FF", "LD_A_SET_7_ptr_IX_d"},
}};

inline constexpr std::array<TestOpcodeInfo, 256> TestOpcodeTableFDCB = {{
    {"FD CB __ 00", "LD_B_RLC_ptr_IY_d"},
    {"FD CB __ 01", "LD_C_RLC_ptr_IY_d"},
    {"FD CB __ 02", "LD_D_RLC_ptr_IY_d"},
    {"FD CB __ 03", "LD_E_RLC_ptr_IY_d"},
    {"FD CB __ 04", "LD_H_RLC_ptr_IY_d"},
    {"FD CB __ 05", "LD_L_RLC_ptr_IY_d"},
    {"FD CB __ 06", "RLC_ptr_IY_d"},
    {"FD CB __ 07", "LD_A_RLC_ptr_IY_d"},
    {"FD CB __ 08", "LD_B_RRC_ptr_IY_d"},
    {"FD CB __ 09", "LD_C_RRC_ptr_IY_d"},
    {"FD CB __ 0A", "LD_D_RRC_ptr_IY_d"},
    {"FD CB __ 0B", "LD_E_RRC_ptr_IY_d"},
    {"FD CB __ 0C", "LD_H_RRC_ptr_IY_d"},
    {"FD CB __ 0D", "LD_L_RRC_ptr_IY_d"},
    {"FD CB __ 0E", "RRC_ptr_IY_d"},
    {"FD CB __ 0F", "LD_A_RRC_ptr_IY_d"},
    {"FD CB __ 10", "LD_B_RL_ptr_IY_d"},
    {"FD CB __ 11", "LD_C_RL_ptr_IY_d"},
    {"FD CB __ 12", "LD_D_RL_ptr_IY_d"},
    {"FD CB __ 13", "LD_E_RL_ptr_IY_d"},
    {"FD CB __ 14", "LD_H_RL_ptr_IY_d"},
    {"FD CB __ 15", "LD_L_RL_ptr_IY_d"},
    {"FD CB __ 16", "RL_ptr_IY_d"},
    {"FD CB __ 17", "LD_A_RL_ptr_IY_d"},
    {"FD CB __ 18", "LD_B_RR_ptr_IY_d"},
    {"FD CB __ 19", "LD_C_RR_ptr_IY_d"},
    {"FD CB __ 1A", "LD_D_RR_ptr_IY_d"},
    {"FD CB __ 1B", "LD_E_RR_ptr_IY_d"},
    {"FD CB __ 1C", "LD_H_RR_ptr_IY_d"},
    {"FD CB __ 1D", "LD_L_RR_ptr_IY_d"},
    {"FD CB __ 1E", "RR_ptr_IY_d"},
    {"FD CB __ 1F", "LD_A_RR_ptr_IY_d"},
    {"FD CB __ 20", "LD_B_SLA_ptr_IY_d"},
    {"FD CB __ 21", "LD_C_SLA_ptr_IY_d"},
    {"FD CB __ 22", "LD_D_SLA_ptr_IY_d"},
    {"FD CB __ 23", "LD_E_SLA_ptr_IY_d"},
    {"FD CB __ 24", "LD_H_SLA_ptr_IY_d"},
    {"FD CB __ 25", "LD_L_SLA_ptr_IY_d"},
    {"FD CB __ 26", "SLA_ptr_IY_d"},
    {"FD CB __ 27", "LD_A_SLA_ptr_IY_d"},
    {"FD CB __ 28", "LD_B_SRA_ptr_IY_d"},
    {"FD CB __ 29", "LD_C_SRA_ptr_IY_d"},
    {"FD CB __ 2A", "LD_D_SRA_ptr_IY_d"},
    {"FD CB __ 2B", "LD_E_SRA_ptr_IY_d"},
    {"FD CB __ 2C", "LD_H_SRA_ptr_IY_d"},
    {"FD CB __ 2D", "LD_L_SRA_ptr_IY_d"},
    {"FD CB __ 2E", "SRA_ptr_IY_d"},
    {"FD CB __ 2F", "LD_A_SRA_ptr_IY_d"},
    {"FD CB __ 30", "LD_B_SLL_ptr_IY_d"},
    {"FD CB __ 31", "LD_C_SLL_ptr_IY_d"},
    {"FD CB __ 32", "LD_D_SLL_ptr_IY_d"},
    {"FD CB __ 33", "LD_E_SLL_ptr_IY_d"},
    {"FD CB __ 34", "LD_H_SLL_ptr_IY_d"},
    {"FD CB __ 35", "LD_L_SLL_ptr_IY_d"},
    {"FD CB __ 36", "SLL_ptr_IY_d"},
    {"FD CB __ 37", "LD_A_SLL_ptr_IY_d"},
    {"FD CB __ 38", "LD_B_SRL_ptr_IY_d"},
    {"FD CB __ 39", "LD_C_SRL_ptr_IY_d"},
    {"FD CB __ 3A", "LD_D_SRL_ptr_IY_d"},
    {"FD CB __ 3B", "LD_E_SRL_ptr_IY_d"},
    {"FD CB __ 3C", "LD_H_SRL_ptr_IY_d"},
    {"FD CB __ 3D", "LD_L_SRL_ptr_IY_d"},
    {"FD CB __ 3E", "SRL_ptr_IY_d"},
    {"FD CB __ 3F", "LD_A_SRL_ptr_IY_d"},
    {"FD CB __ 40", "BIT_0_ptr_IY_d"},
    {"FD CB __ 41", "BIT_0_ptr_IY_d"},
    {"FD CB __ 42", "BIT_0_ptr_IY_d"},
    {"FD CB __ 43", "BIT_0_ptr_IY_d"},
    {"FD CB __ 44", "BIT_0_ptr_IY_d"},
    {"FD CB __ 45", "BIT_0_ptr_IY_d"},
    {"FD CB __ 46", "BIT_0_ptr_IY_d"},
    {"FD CB __ 47", "BIT_0_ptr_IY_d"},
    {"FD CB __ 48", "BIT_1_ptr_IY_d"},
    {"FD CB __ 49", "BIT_1_ptr_IY_d"},
    {"FD CB __ 4A", "BIT_1_ptr_IY_d"},
    {"FD CB __ 4B", "BIT_1_ptr_IY_d"},
    {"FD CB __ 4C", "BIT_1_ptr_IY_d"},
    {"FD CB __ 4D", "BIT_1_ptr_IY_d"},
    {"FD CB __ 4E", "BIT_1_ptr_IY_d"},
    {"FD CB __ 4F", "BIT_1_ptr_IY_d"},
    {"FD CB __ 50", "BIT_2_ptr_IY_d"},
    {"FD CB __ 51", "BIT_2_ptr_IY_d"},
    {"FD CB __ 52", "BIT_2_ptr_IY_d"},
    {"FD CB __ 53", "BIT_2_ptr_IY_d"},
    {"FD CB __ 54", "BIT_2_ptr_IY_d"},
    {"FD CB __ 55", "BIT_2_ptr_IY_d"},
    {"FD CB __ 56", "BIT_2_ptr_IY_d"},
    {"FD CB __ 57", "BIT_2_ptr_IY_d"},
    {"FD CB __ 58", "BIT_3_ptr_IY_d"},
    {"FD CB __ 59", "BIT_3_ptr_IY_d"},
    {"FD CB __ 5A", "BIT_3_ptr_IY_d"},
    {"FD CB __ 5B", "BIT_3_ptr_IY_d"},
    {"FD CB __ 5C", "BIT_3_ptr_IY_d"},
    {"FD CB __ 5D", "BIT_3_ptr_IY_d"},
    {"FD CB __ 5E", "BIT_3_ptr_IY_d"},
    {"FD CB __ 5F", "BIT_3_ptr_IY_d"},
    {"FD CB __ 60", "BIT_4_ptr_IY_d"},
    {"FD CB __ 61", "BIT_4_ptr_IY_d"},
    {"FD CB __ 62", "BIT_4_ptr_IY_d"},
    {"FD CB __ 63", "BIT_4_ptr_IY_d"},
    {"FD CB __ 64", "BIT_4_ptr_IY_d"},
    {"FD CB __ 65", "BIT_4_ptr_IY_d"},
    {"FD CB __ 66", "BIT_4_ptr_IY_d"},
    {"FD CB __ 67", "BIT_4_ptr_IY_d"},
    {"FD CB __ 68", "BIT_5_ptr_IY_d"},
    {"FD CB __ 69", "BIT_5_ptr_IY_d"},
    {"FD CB __ 6A", "BIT_5_ptr_IY_d"},
    {"FD CB __ 6B", "BIT_5_ptr_IY_d"},
    {"FD CB __ 6C", "BIT_5_ptr_IY_d"},
    {"FD CB __ 6D", "BIT_5_ptr_IY_d"},
    {"FD CB __ 6E", "BIT_5_ptr_IY_d"},
    {"FD CB __ 6F", "BIT_5_ptr_IY_d"},
    {"FD CB __ 70", "BIT_6_ptr_IY_d"},
    {"FD CB __ 71", "BIT_6_ptr_IY_d"},
    {"FD CB __ 72", "BIT_6_ptr_IY_d"},
    {"FD CB __ 73", "BIT_6_ptr_IY_d"},
    {"FD CB __ 74", "BIT_6_ptr_IY_d"},
    {"FD CB __ 75", "BIT_6_ptr_IY_d"},
    {"FD CB __ 76", "BIT_6_ptr_IY_d"},
    {"FD CB __ 77", "BIT_6_ptr_IY_d"},
    {"FD CB __ 78", "BIT_7_ptr_IY_d"},
    {"FD CB __ 79", "BIT_7_ptr_IY_d"},
    {"FD CB __ 7A", "BIT_7_ptr_IY_d"},
    {"FD CB __ 7B", "BIT_7_ptr_IY_d"},
    {"FD CB __ 7C", "BIT_7_ptr_IY_d"},
    {"FD CB __ 7D", "BIT_7_ptr_IY_d"},
    {"FD CB __ 7E", "BIT_7_ptr_IY_d"},
    {"FD CB __ 7F", "BIT_7_ptr_IY_d"},
    {"FD CB __ 80", "LD_B_RES_0_ptr_IY_d"},
    {"FD CB __ 81", "LD_C_RES_0_ptr_IY_d"},
    {"FD CB __ 82", "LD_D_RES_0_ptr_IY_d"},
    {"FD CB __ 83", "LD_E_RES_0_ptr_IY_d"},
    {"FD CB __ 84", "LD_H_RES_0_ptr_IY_d"},
    {"FD CB __ 85", "LD_L_RES_0_ptr_IY_d"},
    {"FD CB __ 86", "RES_0_ptr_IY_d"},
    {"FD CB __ 87", "LD_A_RES_0_ptr_IY_d"},
    {"FD CB __ 88", "LD_B_RES_1_ptr_IY_d"},
    {"FD CB __ 89", "LD_C_RES_1_ptr_IY_d"},
    {"FD CB __ 8A", "LD_D_RES_1_ptr_IY_d"},
    {"FD CB __ 8B", "LD_E_RES_1_ptr_IY_d"},
    {"FD CB __ 8C", "LD_H_RES_1_ptr_IY_d"},
    {"FD CB __ 8D", "LD_L_RES_1_ptr_IY_d"},
    {"FD CB __ 8E", "RES_1_ptr_IY_d"},
    {"FD CB __ 8F", "LD_A_RES_1_ptr_IY_d"},
    {"FD CB __ 90", "LD_B_RES_2_ptr_IY_d"},
    {"FD CB __ 91", "LD_C_RES_2_ptr_IY_d"},
    {"FD CB __ 92", "LD_D_RES_2_ptr_IY_d"},
    {"FD CB __ 93", "LD_E_RES_2_ptr_IY_d"},
    {"FD CB __ 94", "LD_H_RES_2_ptr_IY_d"},
    {"FD CB __ 95", "LD_L_RES_2_ptr_IY_d"},
    {"FD CB __ 96", "RES_2_ptr_IY_d"},
    {"FD CB __ 97", "LD_A_RES_2_ptr_IY_d"},
    {"FD CB __ 98", "LD_B_RES_3_ptr_IY_d"},
    {"FD CB __ 99", "LD_C_RES_3_ptr_IY_d"},
    {"FD CB __ 9A", "LD_D_RES_3_ptr_IY_d"},
    {"FD CB __ 9B", "LD_E_RES_3_ptr_IY_d"},
    {"FD CB __ 9C", "LD_H_RES_3_ptr_IY_d"},
    {"FD CB __ 9D", "LD_L_RES_3_ptr_IY_d"},
    {"FD CB __ 9E", "RES_3_ptr_IY_d"},
    {"FD CB __ 9F", "LD_A_RES_3_ptr_IY_d"},
    {"FD CB __ A0", "LD_B_RES_4_ptr_IY_d"},
    {"FD CB __ A1", "LD_C_RES_4_ptr_IY_d"},
    {"FD CB __ A2", "LD_D_RES_4_ptr_IY_d"},
    {"FD CB __ A3", "LD_E_RES_4_ptr_IY_d"},
    {"FD CB __ A4", "LD_H_RES_4_ptr_IY_d"},
    {"FD CB __ A5", "LD_L_RES_4_ptr_IY_d"},
    {"FD CB __ A6", "RES_4_ptr_IY_d"},
    {"FD CB __ A7", "LD_A_RES_4_ptr_IY_d"},
    {"FD CB __ A8", "LD_B_RES_5_ptr_IY_d"},
    {"FD CB __ A9", "LD_C_RES_5_ptr_IY_d"},
    {"FD CB __ AA", "LD_D_RES_5_ptr_IY_d"},
    {"FD CB __ AB", "LD_E_RES_5_ptr_IY_d"},
    {"FD CB __ AC", "LD_H_RES_5_ptr_IY_d"},
    {"FD CB __ AD", "LD_L_RES_5_ptr_IY_d"},
    {"FD CB __ AE", "RES_5_ptr_IY_d"},
    {"FD CB __ AF", "LD_A_RES_5_ptr_IY_d"},
    {"FD CB __ B0", "LD_B_RES_6_ptr_IY_d"},
    {"FD CB __ B1", "LD_C_RES_6_ptr_IY_d"},
    {"FD CB __ B2", "LD_D_RES_6_ptr_IY_d"},
    {"FD CB __ B3", "LD_E_RES_6_ptr_IY_d"},
    {"FD CB __ B4", "LD_H_RES_6_ptr_IY_d"},
    {"FD CB __ B5", "LD_L_RES_6_ptr_IY_d"},
    {"FD CB __ B6", "RES_6_ptr_IY_d"},
    {"FD CB __ B7", "LD_A_RES_6_ptr_IY_d"},
    {"FD CB __ B8", "LD_B_RES_7_ptr_IY_d"},
    {"FD CB __ B9", "LD_C_RES_7_ptr_IY_d"},
    {"FD CB __ BA", "LD_D_RES_7_ptr_IY_d"},
    {"FD CB __ BB", "LD_E_RES_7_ptr_IY_d"},
    {"FD CB __ BC", "LD_H_RES_7_ptr_IY_d"},
    {"FD CB __ BD", "LD_L_RES_7_ptr_IY_d"},
    {"FD CB __ BE", "RES_7_ptr_IY_d"},
    {"FD CB __ BF", "LD_A_RES_7_ptr_IY_d"},
    {"FD CB __ C0", "LD_B_SET_0_ptr_IY_d"},
    {"FD CB __ C1", "LD_C_SET_0_ptr_IY_d"},
    {"FD CB __ C2", "LD_D_SET_0_ptr_IY_d"},
    {"FD CB __ C3", "LD_E_SET_0_ptr_IY_d"},
    {"FD CB __ C4", "LD_H_SET_0_ptr_IY_d"},
    {"FD CB __ C5", "LD_L_SET_0_ptr_IY_d"},
    {"FD CB __ C6", "SET_0_ptr_IY_d"},
    {"FD CB __ C7", "LD_A_SET_0_ptr_IY_d"},
    {"FD CB __ C8", "LD_B_SET_1_ptr_IY_d"},
    {"FD CB __ C9", "LD_C_SET_1_ptr_IY_d"},
    {"FD CB __ CA", "LD_D_SET_1_ptr_IY_d"},
    {"FD CB __ CB", "LD_E_SET_1_ptr_IY_d"},
    {"FD CB __ CC", "LD_H_SET_1_ptr_IY_d"},
    {"FD CB __ CD", "LD_L_SET_1_ptr_IY_d"},
    {"FD CB __ CE", "SET_1_ptr_IY_d"},
    {"FD CB __ CF", "LD_A_SET_1_ptr_IY_d"},
    {"FD CB __ D0", "LD_B_SET_2_ptr_IY_d"},
    {"FD CB __ D1", "LD_C_SET_2_ptr_IY_d"},
    {"FD CB __ D2", "LD_D_SET_2_ptr_IY_d"},
    {"FD CB __ D3", "LD_E_SET_2_ptr_IY_d"},
    {"FD CB __ D4", "LD_H_SET_2_ptr_IY_d"},
    {"FD CB __ D5", "LD_L_SET_2_ptr_IY_d"},
    {"FD CB __ D6", "SET_2_ptr_IY_d"},
    {"FD CB __ D7", "LD_A_SET_2_ptr_IY_d"},
    {"FD CB __ D8", "LD_B_SET_3_ptr_IY_d"},
    {"FD CB __ D9", "LD_C_SET_3_ptr_IY_d"},
    {"FD CB __ DA", "LD_D_SET_3_ptr_IY_d"},
    {"FD CB __ DB", "LD_E_SET_3_ptr_IY_d"},
    {"FD CB __ DC", "LD_H_SET_3_ptr_IY_d"},
    {"FD CB __ DD", "LD_L_SET_3_ptr_IY_d"},
    {"FD CB __ DE", "SET_3_ptr_IY_d"},
    {"FD CB __ DF", "LD_A_SET_3_ptr_IY_d"},
    {"FD CB __ E0", "LD_B_SET_4_ptr_IY_d"},
    {"FD CB __ E1", "LD_C_SET_4_ptr_IY_d"},
    {"FD CB __ E2", "LD_D_SET_4_ptr_IY_d"},
    {"FD CB __ E3", "LD_E_SET_4_ptr_IY_d"},
    {"FD CB __ E4", "LD_H_SET_4_ptr_IY_d"},
    {"FD CB __ E5", "LD_L_SET_4_ptr_IY_d"},
    {"FD CB __ E6", "SET_4_ptr_IY_d"},
    {"FD CB __ E7", "LD_A_SET_4_ptr_IY_d"},
    {"FD CB __ E8", "LD_B_SET_5_ptr_IY_d"},
    {"FD CB __ E9", "LD_C_SET_5_ptr_IY_d"},
    {"FD CB __ EA", "LD_D_SET_5_ptr_IY_d"},
    {"FD CB __ EB", "LD_E_SET_5_ptr_IY_d"},
    {"FD CB __ EC", "LD_H_SET_5_ptr_IY_d"},
    {"FD CB __ ED", "LD_L_SET_5_ptr_IY_d"},
    {"FD CB __ EE", "SET_5_ptr_IY_d"},
    {"FD CB __ EF", "LD_A_SET_5_ptr_IY_d"},
    {"FD CB __ F0", "LD_B_SET_6_ptr_IY_d"},
    {"FD CB __ F1", "LD_C_SET_6_ptr_IY_d"},
    {"FD CB __ F2", "LD_D_SET_6_ptr_IY_d"},
    {"FD CB __ F3", "LD_E_SET_6_ptr_IY_d"},
    {"FD CB __ F4", "LD_H_SET_6_ptr_IY_d"},
    {"FD CB __ F5", "LD_L_SET_6_ptr_IY_d"},
    {"FD CB __ F6", "SET_6_ptr_IY_d"},
    {"FD CB __ F7", "LD_A_SET_6_ptr_IY_d"},
    {"FD CB __ F8", "LD_B_SET_7_ptr_IY_d"},
    {"FD CB __ F9", "LD_C_SET_7_ptr_IY_d"},
    {"FD CB __ FA", "LD_D_SET_7_ptr_IY_d"},
    {"FD CB __ FB", "LD_E_SET_7_ptr_IY_d"},
    {"FD CB __ FC", "LD_H_SET_7_ptr_IY_d"},
    {"FD CB __ FD", "LD_L_SET_7_ptr_IY_d"},
    {"FD CB __ FE", "SET_7_ptr_IY_d"},
    {"FD CB __ FF", "LD_A_SET_7_ptr_IY_d"},
}};

#endif
